# Generated by Django 2.1.7 on 2019-02-14 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10)),
                ('nama', models.CharField(max_length=100)),
                ('jumlah', models.IntegerField()),
            ],
            options={
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=20)),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('alamat', models.TextField(blank=True)),
                ('telepon', models.CharField(max_length=13)),
            ],
            options={
                'ordering': ['nim'],
            },
        ),
        migrations.CreateModel(
            name='Pinjam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pinjam', models.DateField()),
                ('tanggal_kembali', models.DateField(blank=True, null=True)),
                ('denda', models.IntegerField(blank=True, default=0, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('kode_buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buku.Buku')),
                ('nim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buku.Mahasiswa')),
            ],
            options={
                'ordering': ['tanggal_pinjam'],
            },
        ),
    ]
