# Generated by Django 2.1.7 on 2019-02-14 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buku', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='kode',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pinjam',
            name='kode_buku',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='buku.Buku'),
        ),
    ]
